language:
  - cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
           - qt5-default libqt5svg5-dev autoconf libtool git mercurial

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew install qt5 ; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then export PATH=$PATH:/usr/local/opt/qt5/bin ; fi

before_script:
  - qmake -r easyhg.pro

script:
  - make -j3
