FROM ubuntu:18.04
RUN apt-get update
ADD output/easymercurial_[[RELEASE]]_amd64.deb easymercurial_[[RELEASE]]_amd64.deb
RUN apt install -y ./easymercurial_[[RELEASE]]_amd64.deb
RUN /usr/bin/EasyMercurial --version

