FROM centos:7
RUN yum update
RUN yum -y groupinstall "X Window System"
RUN yum -y install wget
ADD output/EasyMercurial-[[REVISION]]-x86_64.AppImage EasyMercurial.AppImage
RUN chmod +x EasyMercurial.AppImage
RUN ./EasyMercurial.AppImage --appimage-extract
RUN ./squashfs-root/AppRun --version
