FROM centos:7

# Ensure that everything subsequent is re-run when a new revision is
# being built (rather than being cached) - so as to avoid potential
# mismatches between results of yum update and the package dependency
# installation itself
RUN echo [[REVISION]]

RUN yum update
RUN yum -y groupinstall "X Window System"
RUN yum -y install wget
ADD output/EasyMercurial-[[REVISION]]-x86_64.AppImage EasyMercurial.AppImage
RUN chmod +x EasyMercurial.AppImage
RUN ./EasyMercurial.AppImage --appimage-extract
RUN ./squashfs-root/AppRun --version
